#if (LIBNUMA_LIBRARIES AND LIBNUMA_INCLUDE_DIRS)
#  set (LibNuma_FIND_QUIETLY TRUE)
#endif (LIBNUMA_LIBRARIES AND LIBNUMA_INCLUDE_DIRS)

find_path(LIBNUMA_INCLUDE_DIRS NAMES numa.h)
find_library(LIBNUMA_LIBRARIES NAMES numa)

include (FindPackageHandleStandardArgs)
find_package_handle_standard_args(LibNuma DEFAULT_MSG
  LIBNUMA_LIBRARIES
  LIBNUMA_INCLUDE_DIRS)

mark_as_advanced(LIBNUMA_INCLUDE_DIRS LIBNUMA_LIBRARIES)
